import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import { TooltipProvider } from "@/components/ui/tooltip"
import db from "@/connector/db.drizzle"
import { after } from "next/server"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  after(async () => {
    try {
      const result = await db.execute("SELECT 1")
      if (result.count === 1) {
        console.log("Drizzle is initialized and connected to the database.")
      } else {
        throw new Error(
          "Drizzle is not properly initialized or connected to the database."
        )
      }
    } catch (error) {
      console.error("Error initializing Drizzle:", error)
    }
  })
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`antialiased ${geistMono.variable} font-sans ${geistSans.variable}`}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <TooltipProvider>{children}</TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
